# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dpa-newslab.github.io/bbc-newshack-2017
title: 'dpa @ BBC #newsHack 2017 - Social Index' 
email: martin.virtel@dpa-info.com
author: Martin Virtel
description: > # "Write an awesome description for your new site here. 
  Our project at the  BBC #newsHack 2017
copyright: '(c) 2017 dpa-infocom GmbH'
credits: 'dpa-newslab'


baseurl: '/bbc-newshack-2017/'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
